[package]
name = "bevy_gltf_kun"
description = "Bevy glTF plugin using gltf_kun."
keywords = ["bevy", "gltf"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = ["export", "import"]
export = []
import = []

[dependencies]
bevy = { version = "0.12.1", default-features = false, features = [
  "android_shared_stdcxx",
  "animation",
  "bevy_asset",
  "bevy_audio",
  "bevy_core_pipeline",
  "bevy_gilrs",
  "bevy_gizmos",
  "bevy_pbr",
  "bevy_render",
  "bevy_scene",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "bevy_winit",
  "default_font",
  "hdr",
  "multi-threaded",
  "png",
  "tonemapping_luts",
  "vorbis",
  "webgl2",
  "x11"
]}
glam.workspace = true
gltf_kun = { version = "0.0.5", path = "../gltf_kun" }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
bevy_egui = "0.24.0"
bevy_panorbit_camera = "0.10.0"
