[package]
name = "bevy_gltf_kun"
description = "Bevy glTF plugin using gltf_kun."
keywords = ["bevy", "gltf"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bevy = "0.12.1"
glam.workspace = true
gltf_kun = { version = "0.0.3", path = "../gltf_kun" }
serde_json.workspace = true
