[package]
name = "bevy_gltf_kun"
description = "Bevy glTF plugin using gltf_kun."
keywords = ["bevy", "gltf"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = ["export", "import"]
export = []
import = []

[dependencies]
anyhow.workspace = true
bevy = "0.12.1"
glam.workspace = true
gltf_kun = { version = "0.0.4", path = "../gltf_kun" }
serde_json.workspace = true

[dev-dependencies]
bevy_panorbit_camera = "0.10.0"
