[package]
name = "bevy_gltf_kun"
description = "Bevy glTF plugin using gltf_kun."
keywords = ["bevy", "gltf"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.79"
bevy = "0.12.1"
gltf_kun = { version = "0.0.3", path = "../gltf_kun" }
