[package]
name = "bevy_gltf_kun"
description = "Bevy glTF plugin using gltf_kun."
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unavi-xyz/gltf_kun"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = "0.12.0"
gltf_kun = { path = "../gltf_kun" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
