[workspace]
resolver = "2"
members = ["bevy_gltf_kun", "bevy_example", "gltf_kun"]

[workspace.package]
version = "0.0.8"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unavi-xyz/gltf_kun"
edition = "2021"

[workspace.dependencies]
glam = "0.25.0"
gltf_kun = { path = "gltf_kun", version = "0.0.8" }
petgraph = { version = "0.6.4", default-features = false, features = ["stable_graph"] }
serde_json = "1.0.110"
thiserror = "1.0.56"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[patch.crates-io]
bevy = { git = "https://github.com/eero-lehtinen/bevy.git", branch = "v0.13.0-nvidia-fix" }
