[workspace]
resolver = "2"
members = ["bevy_gltf_kun", "gltf_kun"]

[workspace.package]
version = "0.0.4"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unavi-xyz/gltf_kun"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.79"
glam = "0.25.0"
serde_json = "1.0.110"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
