[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unavi-xyz/gltf_kun"
version = "0.1.0"

[workspace.metadata.release]
publish = false
shared-version = true
tag-name = "v{{version}}"

[workspace.dependencies]
avian3d = "0.3.0"
petgraph = { version = "0.8.1", default-features = false, features = [
  "stable_graph",
] }
serde_json = "1.0.140"
thiserror = "2.0.12"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
