[package]
name = "bevy_example"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
avian3d.workspace = true
bevy = { version = "0.15.0", features = ["jpeg"] }
bevy_egui = "0.31.1"
bevy_gltf_kun = { path = "../bevy_gltf_kun", features = ["omi_physics"] }
bevy_panorbit_camera = "0.21.2"
gltf_kun = { path = "../gltf_kun" }
petgraph.workspace = true
wasm-bindgen = "0.2.99"
