[package]
name = "bevy_example"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
bevy = "0.14.0"
bevy_egui = "0.28.0"
bevy_gltf_kun.workspace = true
bevy_panorbit_camera = "0.19.0"
bevy_xpbd_3d.workspace = true
egui_graphs = "0.19.0"
gltf_kun.workspace = true
petgraph.workspace = true
wasm-bindgen = "=0.2.92"
