[package]
name = "gltf_kun"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
gltf = "1.3.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
