[package]
name = "gltf_kun"
description="Extensible library for building glTF toolchains."
keywords = ["gltf"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
glam.workspace = true
gltf = { version = "1.4.0", features = ["extensions", "extras"] }
petgraph = "0.6.4"
serde_json.workspace = true
tracing = "0.1.40"

[dev-dependencies]
tracing-test = "0.2.4"
