[package]
name = "gltf_kun"
description="Extensible library for building glTF toolchains."
keywords = ["gltf"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.79"
glam = "0.25.0"
gltf = { version = "1.4.0", features = ["extensions", "extras"] }
petgraph = "0.6.4"
serde_json = "1.0.110"
